version: '3'
services:
  monitoring:
    image: whois-api:0.0.1
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=5000
      - SECRET_KEY=KNot6996KimciL
      - WORKER=2
      - ENVIRONMENT=development
      - COMMAND=server
      - USERNAME=admin
      - PASSWORD=admin
    command: sh run.sh server production 1