version: '3'
services:
  whois:
    image: whois-api:0.0.1
    ports:
        - "5000:5000"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=5000
      - SECRET_KEY=KNot6996KimciL
      - USERNAME=admin
      - PASSWORD=admin
    command: sh run.sh server production